#!/usr/bin/env python3
"""Write /<slug>/index.html for every case study in index.html's #cs-data.

GitHub Pages has no rewrites, so /soot used to fall through to 404.html: the
panel opened, but the response was a 404 and link previews and crawlers saw
"not found". Each stub is a real file (HTTP 200) carrying that project's title,
description and cover as its preview, then hands the path to the index the
same way 404.html does (/?p=<slug>), which opens the panel and restores /<slug>.

Run after any change to #cs-data or a cover:  python3 scripts/build-routes.py
"""
import html, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = 'https://renaise.com'
src = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
data = json.loads(re.search(r'id="cs-data">(.*?)</script>', src, re.S).group(1))

TPL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title}</title>
<meta name="description" content="{desc}" />
<link rel="canonical" href="{url}" />
<meta property="og:type" content="article" />
<meta property="og:url" content="{url}" />
<meta property="og:title" content="{title}" />
<meta property="og:description" content="{desc}" />
<meta property="og:image" content="{img}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{title}" />
<meta name="twitter:description" content="{desc}" />
<meta name="twitter:image" content="{img}" />
<!-- Generated by scripts/build-routes.py. Do not edit by hand. -->
<script>
(function(){{
  var l = window.location;
  l.replace('/?p={slug}' + (l.search ? '&q=' + encodeURIComponent(l.search.slice(1)) : '') + l.hash);
}})();
</script>
</head>
<body><a href="/?p={slug}">{name}: {case}</a></body>
</html>
"""

for slug, d in data.items():
    e = lambda s: html.escape(str(s or ''), quote=True)
    img = '/stage/%s/cover.jpg' % slug
    if not os.path.exists(os.path.join(ROOT, img.lstrip('/'))):
        img = '/assets/og.jpg'
    out = TPL.format(
        slug=slug, name=e(d.get('name', slug)), case=e(d.get('title', '')),
        # A project whose headline is its own name would otherwise read
        # "Artifice Brand Identity · Artifice Brand Identity · Renaise Kim".
        title=e(' · '.join(
            [p for i, p in enumerate([d.get('name', slug), d.get('title', '')])
             if p and p not in [d.get('name', slug), d.get('title', '')][:i]]
            + ['Renaise Kim'])),
        desc=e(d.get('hook', '')), url=SITE + '/' + slug + '/', img=SITE + img)
    os.makedirs(os.path.join(ROOT, slug), exist_ok=True)
    open(os.path.join(ROOT, slug, 'index.html'), 'w', encoding='utf-8').write(out)
    print('wrote /%s/' % slug)
